### ISSUE TITLE
how can i configure user & password for KMC

### ISSUE THREAD

**Issue by hblg2006sxb** [kaltura/platform-install-packages#548] opened 2016-06-23 02:28 UTC
i have installed kaltura v11.16, and also can visit http://192.168.65.130/kmc normal, but when i type the user & password that i think it's right, it tell me the < the user and password i input is incorret >, now i want to konw, how configure user & password for managing? and where is the file that i can find my user & password i had configured?

**Comment by jessp01** [comment] 2016-06-23 02:53
Hello,

After installing, you should go to http://192.168.65.130/admin_console and input the email and password you provided during the install.
If that does not work, then you probably have an issue with the sphinx or DB being down, you can check what the issue is by running:
\# . /etc/profile.d/kaltura*bash.sh
\# kaltlog

and then try to login and look at the errors being outputted.

If the only issue is that you don't remember the passwd, you can reset it following this procedure:
https://github.com/kaltura/platform-install-packages/blob/Kajam-11.17.0/doc/kaltura-packages-faq.md#cannot-login-to-admin-console

Once logged into the admin console, go to publishers and create a new partner, you can then use this partner to login to KMC.

I am closing this issue since we want to keep the Github's issues section to bug reporting rather than general questions but if you have additional questions, please post them to forum.kaltura.org

**Closed by jessp01** 2016-06-23 02:53 UTC
