### ISSUE TITLE
rpm Couldn't resolve host

### ISSUE THREAD

**Issue by AquileaSFX** [kaltura/platform-install-packages#439] opened 2015-09-07 16:47 UTC
when using yum install kaltura-server

http://installrepo.kaltura.org/releases/latest/RPMS/noarch/repodata/eb97e35560ca41166cda51ee3600142518a46ff87631a2ca1d5b4fac7d9b2fc7-primary.sqlite.bz2: [Errno 14] PYCURL ERROR 6 - "Couldn't resolve host 'installrepo.kaltura.org'"
Trying other mirror.
Error: failure: repodata/eb97e35560ca41166cda51ee3600142518a46ff87631a2ca1d5b4fac7d9b2fc7-primary.sqlite.bz2 from Kaltura-noarch: [Errno 256] No more mirrors to try.

**Comment by jessp01** [comment] 2015-09-07 16:50
Hi Bryan,

This does not reproduce for me so I believe the issue is in your machine.
Does:
\# host installrepo.kaltura.org
return proper results?

from the output you attached it seems installrepo.kaltura.org is not resolved from your host.. are other domains resolvable? perhaps you have a DNS issue?

I am closing this one since its not a global issue but feel free to post at forum.kaltura.org

**Closed by jessp01** 2015-09-07 16:50 UTC

**Comment by AquileaSFX** [comment] 2015-09-07 17:14
Jess, 
sorry to post again, yum is looking for a "eb97e35*

inside http://installrepo.kaltura.org/releases/latest/RPMS/noarch/repodata/

which it not exists.

all inside that folder is generated today, so I believe something is broken.
can you clear your yum cache and try again please?

**Comment by jessp01** [comment] 2015-09-07 17:17
Hi Bryan,

That's a different problem... before you posted "Couldn't resolve host 'installrepo.kaltura.org'", now it seems the CDN edge you are hitting is not yet fully synced.
I would suggest changing installrepo.kaltura.org to installrepo.origin.kaltura.org in your kaltura.repo file and trying again. After you are done upgrading, please revert back to using installrepo.kaltura.org though since, ideally, unless a node is not yet synced, its better to use CDN.

**Comment by AquileaSFX** [comment] 2015-09-07 17:21
Jess,

that did the trick, 
i will revert it back when synced.

thank you.
