### ISSUE TITLE
Kaltura Installation Error - CentOS 7

### ISSUE THREAD

**Issue by DuanelB** [kaltura/platform-install-packages#610] opened 2017-09-06 00:55 UTC
Getting the error listed below - what am I doing wrong?

Error: Package: kaltura-mediainfo-0.7.61-6.x86_64 (Kaltura)
Requires: libzen = 0.4.35
Available: libzen-0.4.34-1.el7.x86_64 (Kaltura)
libzen = 0.4.34-1.el7
Installing: libzen-0.4.36-1.el7.x86_64 (epel)
libzen = 0.4.36-1.el7
Error: Package: kaltura-libmediainfo-0.7.61-6.x86_64 (Kaltura)
Requires: libzen = 0.4.35
Available: libzen-0.4.34-1.el7.x86_64 (Kaltura)
libzen = 0.4.34-1.el7
Installing: libzen-0.4.36-1.el7.x86_64 (epel)
libzen = 0.4.36-1.el7
Error: Package: kaltura-mediainfo-0.7.61-6.x86_64 (Kaltura)
Requires: libzen = 0.4.35
Available: libzen-0.4.34-1.el7.x86_64 (Kaltura)
libzen = 0.4.34-1.el7
Available: libzen-0.4.36-1.el7.x86_64 (epel)
libzen = 0.4.36-1.el7
You could try using --skip-broken to work around the problem
You could try running: rpm -Va --nofiles --nodigest
[root@localhost ~]# yum --showduplicates list libzen | expand
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
removed
Available Packages
libzen.x86_64 0.4.34-1.el7 Kaltura
libzen.x86_64 0.4.36-1.el7 epel
[root@localhost ~]#

**Comment by jessp01** [comment] 2017-09-06 10:08
Hello @DuanelB,

Thank you for your report. The issue is now fixed.
Since we're using CDN, it may take a little while for all edges to sync with the origin server.
If you're having issues with fetching http://installrepo.kaltura.org/releases/rhel7/RPMS/x86_64/repodata, please edit /etc/yum.repos.d/kaltura.repo and replace 'installrepo.kaltura.org' with 'installrepo.origin.kaltura.org'.

Do let me know if you encounter additional issues.

Thanks again,

**Comment by jessp01** [comment] 2017-09-07 12:52
Hi @DuanelB - can you please confirm that all is well?

**Comment by DuanelB** [comment] 2017-09-07 13:12
Hi @jessp01,

Thank you very much for your assistance; I had to use installrepo.origin...That worked for me.

I just got around to trying the installation again.

Thank you again.

**Comment by jessp01** [comment] 2017-09-07 13:20
Thanks for confirming, @DuanelB :)
Closing the issue then.

**Closed by jessp01** 2017-09-07 13:20 UTC
