### ISSUE TITLE
Ubuntu Bionic Beaver 18.04 Packages?

### ISSUE THREAD

**Issue by wowcut** [kaltura/platform-install-packages#638] opened 2018-10-25 19:04 UTC
Ubuntu Bionic Beaver 18.04 Packages? Where can I find them?

**Comment by AdonIrani** [comment] 2020-03-18 02:54
May I request an update on this? Based on the documentation, it would seem like MySQL 5.5 is the only supported database. Is there support for MySQL 8.0? The install guides are now several major versions behind. Would love to know the current status as I'd like to install the server.

**Comment by Schwaitz** [comment] 2020-05-11 21:28
Agreed with @AdonIrani. Can installed all-in-one on 18.04?

**Comment by supersexy** [comment] 2020-06-05 16:19
WHat about Ubuntu 20.04? Why are you so behind - what kind of help do you need to support current distros? Obviously something is not going well with your deployment process.

**Comment by jessp01** [comment] 2020-06-10 10:49
Hello all,

See my reply here: https://forum.kaltura.org/t/support-for-ubuntu-18-04-or-20-04/10230/2
I'm afraid we will not be advancing to MySQL 8.0 at present time and MySQL 5.6 will still be required.
This is due to major changes made in MySQL 5.7, pertaining mostly to strict mode. While we acknowledge that supporting newer MySQL versions is a laudable effort, at present time, we feel our development efforts should be focused on other areas.

@supersexy - criticising one's work is very easy indeed. If you truly wish to contribute to this project, you are welcome to do so. I refer you to my comment to you on the other issue you've opened (https://github.com/kaltura/platform-install-packages/issues/668#issuecomment-639632837) to which you never responded.

**Comment by skaos** [comment] 2020-06-23 02:51
Can you elaborate on the mysql 5.7+ strict mode problems ? What are the major issues ?

Thanks!

**Comment by jessp01** [comment] 2020-06-23 09:01
Hello @skaos ,

Yes, of course.
With MySQL 5.6 and above, one would get errors such as:
> 2017-06-23 20:43:22 [0.001634] [127.0.0.1] [289044709] [7] [API] [KalturaStatement->execute] DEBUG: /* jessex[289044709][propel] */ SELECT permission.ID, permission.TYPE, permission.NAME, permission.FRIENDLY_NAME, permission.DESCRIPTION, permission.PARTNER_ID, permission.STATUS, permission.DEPENDS_ON_PERMISSION_NAMES, permission.TAGS, permission.CREATED_AT, permission.UPDATED_AT, permission.CUSTOM_DATA FROM `permission` WHERE permission.PARTNER_ID IN ('','0') AND permission.NAME IN ('FEATURE_END_USER_REPORTS','FEATURE_ENTITLEMENT') AND permission.STATUS='1' GROUP BY permission.NAME
2017-06-23 20:43:22 [0.012748] [127.0.0.1] [289044709] [8] [API] [BasePeer::doSelect] ERR: Exception: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'kaltura.permission.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in
/opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/vendor/propel/Propel.php(408):
KalturaLog::err('SQLSTATE[42000]...')

The problem is that in order to fix these error we need to use `doSelectStmt` and select only the group by columns.
This makes the query non-cacheable by the query cache, and since it's one of the most common
queries in the system, this is undesirable.

There are also issues with the DB populations scripts under /opt/kaltura/app/deployment/base/sql but these are far easier to fix, albeit a boring task:)

With MySQL 5.6, most issues can be bypassed by setting:

> sql_mode = NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

But 5.7 is even stricter and so, exposes additional issues. There are also some issues with DWH (Data warehouse - the analytics system, which also uses MySQL).

**Comment by skaos** [comment] 2020-06-23 20:33
Thanks for the informations. I will be part of a project using kaltura at my University this fall, i will play with it this summer and i would really like the support of new mysql version (our dba is on 8 and hes not liking me when i try to introduce a new 5.6 cluster ;p). I will try to submit some PR :)

Thanks for your works!

skaos

**Comment by jessp01** [comment] 2020-07-09 16:49
Hi all,

See https://forum.kaltura.org/t/kaltura-ce-16-5-0-released/10551

Cheers,

**Closed by jessp01** 2020-07-09 16:49 UTC
